//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> startWorkYear { get; set; }
        public Nullable<int> departmentID { get; set; }
    }
}
