//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFactory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AFactoryEntities : DbContext
    {
        public AFactoryEntities()
            : base("name=AFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeesShift> employeesShifts { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usersSession> usersSessions { get; set; }
    }
}
